# Generated by Django 4.1.5 on 2023-06-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myusers',
            options={'managed': False},
        ),
    ]
